config/routes.rb
MyStore::Application.routes.draw do

  root to: "pages#frontpage"

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :items do
    get :upvote,    on: :member
    get :expensive, on: :collection
    get :crop_image, on: :member
    put :crop_image, on: :member
  end

  get "admin/users_count" => "admin#users_count"

  # match ':controller(/:action(/:id))(.:format)'
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  has_many :comments, as: :commentable
end

app/models/cart.rb
class Cart < ActiveRecord::Base

  has_many   :positions
  belongs_to :user
  has_many   :items, through: :positions

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/item.rb
class Item < ActiveRecord::Base

  attr_reader :image_crop_data
  validates :price, numericality: { greater_than: 0, allow_nil: true }

  validates :name, presence: true
  has_many :positions
  has_many :carts, through: :positions

  has_many :comments, as: :commentable
  has_and_belongs_to_many :orders

  mount_uploader :image, ImageUploader

  include Redis::Objects
  counter :views

  def crop_image!(c)
    c.each { |k,v| c[k] = v.to_i }
    @image_crop_data = c
    image.recreate_versions!
  end

end

app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :user
  has_and_belongs_to_many :items

  def calculate_total
    write_attribute :total, items.map(&:price).inject(:+)
  end


end

app/models/position.rb
class Position < ActiveRecord::Base

  belongs_to :item
  belongs_to :cart
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one  :cart
  has_many :orders
  has_many :comments

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  before_filter :check_if_admin

  def users_count
    @users_count = User.count
    render layout: "admin"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  private

    def render_403
      render file: "public/403.html", status: 403
    end

    def render_404
      render file: "public/404.html", status: 404
    end

    def check_if_admin
      render_403 unless params[:admin]
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :find_item,      only: [:show, :edit, :update, :destroy, :upvote, :crop_image]
  #before_filter :check_if_admin, only: [:edit, :update, :new, :create, :destroy]

  def index
    @items = Item
    @items = @items.where("price >= ?", params[:price_from])       if params[:price_from]
    @items = @items.where("created_at >= ?", 1.day.ago)            if params[:today]
    @items = @items.where("votes_count >= ?", params[:votes_from]) if params[:votes_from]
    @items = @items.order("votes_count DESC", "price")
  end

  def expensive
    @items = Item.where("price > 1000")
    render "index"
  end

  # /items/1 GET
  def show
    unless @item
      render text: "Page not found", status: 404
    end
    @item.views.increment
  end

  # /items/new GET
  def new
    @item = Item.new
  end

  # /items/1/edit GET
  def edit
  end

  # /items POST
  def create
    @item = Item.create(item_params)
    if @item.errors.empty?
      redirect_to crop_image_item_path(@item)
    else
      render "new"
    end
  end

  # /items/1 PUT
  def update
    @item.update_attributes(item_params)
    if @item.errors.empty?
      redirect_to crop_image_item_path(@item)
    else
      render "edit"
    end
  end

  # /items/1 DELETE
  def destroy
    @item.destroy
    render json: { success: true }
    ItemsMailer.item_destroyed(@item).deliver_now
  end

  def upvote
    @item.increment!(:votes_count)
    redirect_to action: :index
  end

  def crop_image
    if request.put?
      @item.crop_image!(params[:item][:image_crop_data])
      redirect_to item_path(@item)
    end
  end

  private

    def find_item
      @item = Item.where(id: params[:id]).first
      render_404 unless @item
    end

    def item_params
      params.require(:item).permit(:price, :weight, :real, :name, :image)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def frontpage
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create

    build_resource(sign_up_params)

    if verify_recaptcha
      super
    else
      flash.now[:error] = "Incorrect recaptcha! Please try again."
      render "new"
    end

  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title
    if ['show', 'new', 'edit'].include?(params[:action])
      "#{@page_title} | #{params[:controller].capitalize}"
    else
      @page_title
    end
  end

  def urls_to_images(s)
    s.gsub! /\s(http:\/\/.*?\.(png|jpg))\s/,
            '<p><img src="\1"/></p>'
    s.html_safe
  end

  def urls_to_links(s)
    s.gsub! /\s(http:\/\/.*?)\s/,
            '<a href="\1">\1</a>'
    s.html_safe
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/users_count.html.erb
There are <%= @users_count %> on the site.

app/views/items/_form.html.haml
= f.input :price
= f.input :name
= f.input :description
= f.input :weight
= f.input :image

= hidden_field_tag :admin, params[:admin]

app/views/items/crop_image.html.erb
<%= form_for @item, url: crop_image_item_path(@item), method: :put do |f| %>
  <%= image_tag @item.image, id: 'crop_image'%>
  <%= hidden_field_tag :admin, 1 %>
  <%= f.fields_for :image_crop_data do |c| %>
    <%= c.hidden_field :x %>
    <%= c.hidden_field :y %>
    <%= c.hidden_field :width %>
    <%= c.hidden_field :height %>
  <% end %>
  <%= f.submit "Crop image!" %>
<% end %>

app/views/items/edit.html.erb
<h1>Edit item</h1>

<%= form_for @item do |f| %>

  <%= render partial: "form", locals: { f: f } %>
  <p><%= f.submit "Сохранить товар" %></p>

<% end %>

app/views/items/index.html.erb
<% @page_description = "List of all the items in our store" %>
<% @page_keywords = "buy purchase items online store cheap" %>

<h1><%= @page_title = "List of all items" %></h1>

<% if @items.empty? %>
  <b>No items in store</b>
<% else %>
<table class="items">
  <tr>
    <th>item id</th>
    <th>Name</th>
    <th>Price</th>
    <th>Добавлено</th>
    <th></th>
    <th>Рейтинг</th>
  </tr>

  <% @items.each do |i| %>

    <tr data-item_id="<%= i.id %>">
      <td><%= i.id %></td>
      <td><%= image_tag i.image.thumb %> <%= link_to i.name, item_path(i) %></td>
      <td><%= i.price %> руб.</td>
      <td><%= i.created_at.to_s.sub("2012", "2013") %></td>
      <td><span class="deleteAction">Удалить</span></td>
      <td><%= i.votes_count %>, <%= link_to "+", upvote_item_path(i) %></td>
    </tr>

  <% end %>

</table>
<% end %>

app/views/items/new.html.haml
%h1 Create new item

= simple_form_for @item do |f|

  = render partial: "form", locals: { f: f }
  %p= f.submit "Создать товар"

app/views/items/show.html.haml
%h1= @page_title = @item.name
%p= image_tag @item.image.normal unless @item.image.blank?

%ul
  %li= "#{@item.price} руб."
  %li= urls_to_links(urls_to_images(@item.description)) 
  %li Вес: #{@item.weight} кг.
  %li Просмотров: <b>#{@item.views.value}</b>

= render partial: "shared/email"

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="adminPanel">
    ADMIN
  </div>

  <div class="sessionInfo">
    <% if current_user %>
      <%= current_user.login %> | <%= link_to "Sign out", destroy_user_session_path %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path %> | <%= link_to "Registration",new_user_registration_path %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

    = display_meta_tags(site: "MyStore", title: page_title, reverse: true, description: @page_description, keywords: @page_keywords)

  %body

    .sessionInfo
      - if current_user
        = current_user.login
        | #{link_to "Sign out", destroy_user_session_path}
      - else
        = link_to "Sign in", new_user_session_path
        | #{link_to "Registration",new_user_registration_path}

    - if flash[:error]
      .flash.error= flash[:error]
    - if flash[:success]
      .flash.success= flash[:success]

    = yield

app/views/pages/frontpage.html.haml
%h1 Welcome to MyStore!
%h2= link_to "See al our available items", items_path

app/views/shared/_email.html.erb
<div class="email">

По всем вопросам обращайтесь на
<script type="text/javascript"><!--
var aixccwp = ['i','i','>','@','t','r','<','.','"','/','=','h','a','n','a','u','a','a','@','a','b','=','m','a','r','a','r','"','c','l','s','"','s','a',' ','n','e','m','b','.','h','"','a','b','a','a',' ','r','s','s','n','f','r','s','e','>','i','u','r','n',':','s','s','<','l','h','s','i','l','i','b','o','i','r'];var fsklvjp = [11,29,50,22,13,52,0,32,35,71,7,23,1,55,46,34,10,63,57,18,61,42,45,24,68,39,62,8,37,38,56,43,21,53,36,65,44,9,51,67,58,49,72,26,28,59,2,4,25,40,30,6,17,60,5,73,64,69,33,20,15,41,66,70,12,3,31,54,48,47,16,14,19,27];var lqnbuaw= new Array();for(var i=0;i<fsklvjp.length;i++){lqnbuaw[fsklvjp[i]] = aixccwp[i]; }for(var i=0;i<lqnbuaw.length;i++){document.write(lqnbuaw[i]);}
// --></script>
<noscript>Please enable Javascript to see the email address</noscript>

</div>